## 넘파이 고속 처리 체험

In [1]:
# 사용할 라이브러리 가져오기
import numpy as np
import time
from numpy.random import rand

In [2]:
# 행, 열의 크기
N = 100

# 행렬의 초기화
matrix_A = np.array(rand(N, N))
matrix_B = np.array(rand(N, N))
matrix_C = np.array([[0] * N for _ in range(N)])

In [3]:
# 파이썬으로 계산
start = time.time()

# for 문을 사용하여 행렬 곱셈 실행
for i in range(N):
    for j in range(N):
        for k in range(N):
            matrix_C[i][j] = matrix_A[i][k] * matrix_B[k][j]
            
print('Time with Python = %.2f[sec]' % float(time.time() - start))

Time with Python = 1.06[sec]


In [4]:
# 넘파이로 계산
start = time.time()

# Numpy를 사용하여 행렬 곱셈 실행
matrix_C = np.dot(matrix_A, matrix_B)

print('Time with Numpy = %.2f[sec]' % float(time.time() - start))

Time with Numpy = 0.01[sec]


##  넘파이 array() 함수로 배열 만들기

In [5]:
# 1차원 배열 (벡터)
array_1D = np.array([1,2,3,4,5,6,7,8])
print(array_1D)
print(type(array_1D))
print('')

# 2차원 배열 (행렬)
array_2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2D)
print(type(array_2D))
print('')

# 3차원 배열 (텐서)
array_3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array_3D)
print(type(array_3D))
print('')

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>



## 인덱스 참조와 슬라이스

In [6]:
# 1차원 배열 (벡터)
print('The first element of 1D Array = ', array_1D[0])
print('The last element of 1D Array = ', array_1D[-1])
print('')
# 2차원 배열 (행렬)
print('1 row x 2 column of 2D Array = ', array_2D[0][1])
print('2 row x 3 column of 2D Array = ', array_2D[1][2])
print('')
# 3차원 배열 (텐서)
print('1 x 2 row x 2 column of 3D Array = ', array_3D[0][1][1])
print('2 x 2 row x 2 column of 3D Array = ', array_3D[1][1][1])
print('')

The first element of 1D Array =  1
The last element of 1D Array =  8

1 row x 2 column of 2D Array =  2
2 row x 3 column of 2D Array =  7

1 x 2 row x 2 column of 3D Array =  4
2 x 2 row x 2 column of 3D Array =  8



## 난수 생성 

In [7]:
# 난수 생성 함수 가져오기
from numpy.random import rand, randint, normal

# 0 이상 1 미만의 난수를 x개 생성
x = 10
random_number1 = rand(x)
print(random_number1)
print('')

# x 이상 y 미만의 정수 난수를 z개 생성
x = 1
y = 1000
z = (2,5)  # 2 rows x 5 columns 행렬
random_number2 = randint(x,y,z)
print(random_number2)
print('')

# 가우스 분포를 따르는 난수를 n개 생성
n = 10
random_number3 = normal(size=n)
print(random_number3)
print('')

[0.34053926 0.99399673 0.16966329 0.8806634  0.19388981 0.77821193
 0.74513712 0.14302479 0.8363005  0.1809963 ]

[[908 193 459 886 108]
 [435 376 265 457 994]]

[-1.90940175 -1.57642634 -0.91330447 -1.59776064 -0.6251729   1.15830699
 -0.69803778 -1.22806539 -0.7197419  -0.64276992]



In [8]:
# 똑같은 난수 생성
from numpy.random import seed
np.random.seed(1234)    # seed 지정함
random_number4 = rand(10)
random_number5 = rand(10)
print(random_number4)
print(random_number5)

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]
[0.35781727 0.50099513 0.68346294 0.71270203 0.37025075 0.56119619
 0.50308317 0.01376845 0.77282662 0.88264119]


In [9]:
np.random.seed(1234)   # seed 지정함
random_number6 = rand(10)
random_number7 = rand(10)
print(random_number6)
print(random_number7)

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]
[0.35781727 0.50099513 0.68346294 0.71270203 0.37025075 0.56119619
 0.50308317 0.01376845 0.77282662 0.88264119]


In [10]:
# seed 지정하지 않음
random_number8 = rand(10)
random_number9 = rand(10)
print(random_number8)
print(random_number9)

[0.36488598 0.61539618 0.07538124 0.36882401 0.9331401  0.65137814
 0.39720258 0.78873014 0.31683612 0.56809865]
[0.86912739 0.43617342 0.80214764 0.14376682 0.70426097 0.70458131
 0.21879211 0.92486763 0.44214076 0.90931596]


In [11]:
# seed 지정하지 않음
random_number10 = rand(10)
random_number11 = rand(10)
print(random_number10)
print(random_number11)

[0.05980922 0.18428708 0.04735528 0.67488094 0.59462478 0.53331016
 0.04332406 0.56143308 0.32966845 0.50296683]
[0.11189432 0.60719371 0.56594464 0.00676406 0.61744171 0.91212289
 0.79052413 0.99208147 0.95880176 0.79196414]


In [12]:
np.random.seed(1234)   # seed 지정함
random_number12 = rand(10)
random_number13 = rand(10)
print(random_number12)
print(random_number13)

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]
[0.35781727 0.50099513 0.68346294 0.71270203 0.37025075 0.56119619
 0.50308317 0.01376845 0.77282662 0.88264119]


## 통계 함수

In [13]:
arr1 = np.arange(15)*2
print('Shape of Array 1 = ', arr1.shape)
print(arr1)
arr2 = np.arange(15).reshape(3,5)*2
print('Shape of Array 2 = ', arr2.shape)
print(arr2)

Shape of Array 1 =  (15,)
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
Shape of Array 2 =  (3, 5)
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [14]:
arr1_sum = np.sum(arr1)
arr2_sum = np.sum(arr2)
print('Sum of Array 1 = ', arr1_sum, '    Sum of Array 2 = ', arr2_sum)

Sum of Array 1 =  210     Sum of Array 2 =  210


In [15]:
arr1_max = np.max(arr1)
arr1_min = np.min(arr1)
arr1_mean = np.mean(arr1)
arr1_average = np.average(arr1)
arr1_argmax = np.argmax(arr1)
arr1_argmin = np.argmin(arr1)
print('Max = ', arr1_max, '   Min = ', arr1_min)
print('Mean = ', arr1_mean, '   Average = ', arr1_average)
print('MaxArg = ', arr1_argmax, '   MinArg = ', arr1_argmin)

Max =  28    Min =  0
Mean =  14.0    Average =  14.0
MaxArg =  14    MinArg =  0


## ndarray 사용시 주의사항

In [16]:
# ndarray를 그대로 대입한 경우
arr1 = np.array([1,2,3,4,5,6])
print('Before: Array 1 = ', arr1)
arr2 = arr1
arr2[0] = 100
print('Array 2 = ', arr2)
print('After: Array 1 = ', arr1)
print('')

# ndarray를 복사해서 대입한 경우
arr1 = np.array([1,2,3,4,5,6])
print('Before: Array 1 = ', arr1)
arr2 = arr1.copy()
arr2[0] = 100
print('Array 2 = ', arr2)
print('After: Array 1 = ', arr1)

Before: Array 1 =  [1 2 3 4 5 6]
Array 2 =  [100   2   3   4   5   6]
After: Array 1 =  [100   2   3   4   5   6]

Before: Array 1 =  [1 2 3 4 5 6]
Array 2 =  [100   2   3   4   5   6]
After: Array 1 =  [1 2 3 4 5 6]


In [17]:
arr1 = np.array([[1,2,3],[4,5,6]])
print('Before reshape: Array 1 = ')
print(arr1)
arr2 = arr1.copy().reshape(3,2)
print('After reshape: Array 2 = ')
print(arr2)

Before reshape: Array 1 = 
[[1 2 3]
 [4 5 6]]
After reshape: Array 2 = 
[[1 2]
 [3 4]
 [5 6]]
